# Generated by Django 3.2 on 2023-09-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField(choices=[(1, '男'), (0, '女')])),
                ('id_card', models.CharField(max_length=18)),
                ('temperature', models.FloatField()),
            ],
            options={
                'db_table': 'personList',
                'permissions': (),
            },
        ),
    ]
